name: Deploy to GitHub Pages

on:
  repository_dispatch:
    types: [makabaka-update]
  push:
    branches:
      - hugo

env:
  PRIVATE_SSH_KEY: ${{ secrets.WUXIDIXI_DEPLOY }} 

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          ssh-key: ${{ secrets.WUXIDIXI_DEPLOY }}   # Fetch all history for .GitInfo and .Lastmod

      - name: Only on repository_dispatch
        # if: ${{ github.event_name == 'repository_dispatch' }} 
        run:  git submodule update --remote

      # - name: Build Link Index
      #   uses: jackyzha0/hugo-obsidian@v2.20
      #   with:
      #     index: true
      #     input: content
      #     output: assets/indices
      #     root: .

      - uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN  }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          cname: googoo-s.github.io
